# Dataset
model_tag: "resnet_LSTM"
dataset: "flickr30k"
data_source: "kaggle"
#dataset_url: "adityajn105"
#image_path: "Images/flickr30k_images"
dataset_url: "srinivasac/flickr30k-dataset"
image_path: "Images"
captions_path: "captions.txt"

# for google drive
#data_source: "google_drive"
#dataset_url: "flickr8k_dataset"
#image_path = "Images"
#captions_path = "captions.txt"
    
# Paths (will be adjusted by setup_paths.py)
artifact_dir: "artifacts"
output_dir: "outputs"
csv_filename: "flickr30k_captions.csv"

# Sampling
num_sample_retrieval: 5

# Device & image
device: "cuda"
size: 224

# Dataloader
batch_size: 64
num_workers: 1

# Training
epochs: 25
patience: 5
embed_size: 400
hidden_size: 512
num_layers: 2
learning_rate: 0.0001
encoder_lr: 1e-4
decoder_lr: 1e-3
encoder_lr2: 1e-5
weight_decay: 0.001
factor: 0.8
attn_dim: 256
dropout: 0.3

use_scheduler: false
attention: 4

attention1:
  embed_size: 400
  hidden_size: 512
  attn_dim: 256
  dropout: 0.15
  encoder_lr: 1e-5
  decoder_lr: 1e-3
  weight_decay: 0.001


attention2:
  embed_size: 600
  hidden_size: 768
  attn_dim: 512
  dropout: 0.4
  encoder_lr: 5e-5
  decoder_lr: 5e-4
  weight_decay: 0.0005

attention3:
  embed_size: 400
  hidden_size: 512
  attn_dim: 256
  dropout: 0.15
  encoder_lr: 1e-5
  decoder_lr: 1e-3
  weight_decay: 0

attention4:
  embed_size: 400
  hidden_size: 512
  attn_dim: 256
  dropout: 0.15
  encoder_lr: 1e-5
  decoder_lr: 1e-3
  weight_decay: 0
  use_scheduler: true

  
# Model
model_name: "resnet50"
pretrained: true
trainable: true
image_embedding: 2048

# Text encoder
text_encoder_model: "distilbert-base-uncased"
text_embedding: 768
text_tokenizer: "distilbert-base-uncased"
max_length: 200

# Projection
num_projection_layers: 1
projection_dim: 256
dropout: 0.3
temperature: 1.0

# Normalization
imagenet_norm:
  mean: [0.485, 0.456, 0.406]
  std:  [0.229, 0.224, 0.225]

flickr8k_norm:
  mean: [0.4580, 0.4461, 0.4039]
  std:  [0.2320, 0.2230, 0.2272]

flickr30k_norm:
  mean: [0.4441, 0.4211, 0.3847]
  std:  [0.2416, 0.2311, 0.2328]

# Debug
#debug: True
debug: False
